 name: Terraform Init, Validate, Plan and Apply
 
 on:
   push:
     branches:
       - 'GCP-infrastructure-setup'
   release:
     types: [created]
 
 jobs:
   terraform:
     runs-on: ubuntu-latest
     environment: GCP_TF
     env:
       tf_version: '0.14.8'
       tf_working_dir: '.'
       tf_bucket_name: ${{ secrets.GCP_BUCKET_NAME }}
       TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
       TF_VAR_name: ${{ secrets.ENV_PREFIX }}
       TF_VAR_region: ${{ secrets.GCP_REGION }}
       TF_VAR_zone: ${{ secrets.GCP_ZONE }}
     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
